version: "3.8"

services:

  apache:
    build: ./apache
    container_name: apache
    restart: unless-stopped
    volumes:
      - ./apache/html:/var/www/html
    networks:
      - backend
    environment:
      - HO=nginx

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/jwt:/var/www/jwt
    networks:
      - backend
    depends_on:
      - apache

  postgres:
    build: ./postgresql
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: authCB
      POSTGRES_USER: authcb
      POSTGRES_PASSWORD: authcb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - backend
    depends_on:
      - postgres

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
